### ISSUE TITLE
Icons Java demo should say why there are two ways to create an icon

### ISSUE THREAD

**Issue by mickoyuh** [vaadin/vaadin-icons-flow#38]
Moved from Gitlab. Reported by Artur. 
--
https://vaadin.com/elements/vaadin-icons/java-examples

"Two ways to create a new icon"

Not very clear WHY this is important to know or why there even are two ways?

**Comment by anasmi** [comment]
Fixed by https://github.com/vaadin/vaadin-icons-flow/pull/71
