### ISSUE TITLE
“All available icons” demo performs poorly

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-icons-flow#64]
### Problem

It takes a long time to render the “All available icons” demo, especially on vaadin.com where the icon bundle is loaded lazily.

### Solution proposals

1. Use a PolymerTemplate for rendering the icons instead of server-side components ([relevant code](https://github.com/vaadin/vaadin-icons-flow/blob/master/vaadin-icons-flow-demo/src/main/java/com/vaadin/flow/component/icon/demo/IconView.java#L94-L117))

2. Use the `.svg` files from https://github.com/vaadin/vaadin-icons/tree/master/assets/svg and the standard `<img src="..." lazyload>` element for rendering the icons
    - The problem here is that the `.svg` files are not part of the npm package, so those would have to be copy-pasted into this repo or the release package would need to be updated to include them (see https://github.com/vaadin/vaadin-icons/issues/82)

**Comment by alvarezguille** [comment]
Solution 1 was implemented. Fixed in #65
